export const coachList = [
    {
        id: '1',
        title: 'Derek March',
        certificate: 'NESTA Certified Personal Fitness Trainer',
        image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FHTB17VSvIFXXXXcUXVXXq6xXFXXXN%2FSummer-Style-2015-Fashion-Brand-Fake-Leather-Men-Sexy-Fitness-Bodybuilding-Funny-T-Shirts-Gay-Skinny.jpg_640x640.jpg&f=1&nofb=1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt neque esse error nisi sunt sapiente impedit a, natus doloremque laudantium, deleniti aspernatur reiciendis, possimus cum cupiditate. Consequatur omnis ipsa, odio sequi quia, tempore repudiandae vero, cupiditate quae earum fugiat veritatis. Dolores dolorum dolorem sint enim atque vel, nobis temporibus voluptates.',
        expertise: 'Endurance, body recompositon, weight loss',
        sessionTime: 45,
        sessionPrice: 300,
        monthPrice: 3300,
        emailAddress: 'testcoach@testcoach.com',
    },
    {
        id: '2',
        title: 'Samantha Gibson',
        certificate: 'ISSA Certified Elite Trainer',
        image: 'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.pngpix.com%2Fwp-content%2Fuploads%2F2016%2F07%2FPNGPIX-COM-Beautiful-Young-Woman-Face-Close-Up-PNG-Image.png&f=1&nofb=1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque, nulla! Aut, soluta quaerat ipsum illo reprehenderit at consequuntur! Dolores officiis quod ipsum? At dolores, eaque veritatis soluta aliquid itaque ipsum.',
        expertise: 'Muscle building, injury recovery',
        sessionTime: 60,
        sessionPrice: 250,
        monthPrice: 1500,
        emailAddress: 'testcoach@testcoach.com',
    },
    {
        id: '3',
        title: 'Aaron Best',
        certificate: 'Certified Nutrition Coach (CNC)',
        image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs3.envato.com%2Ffiles%2F240646545%2FMAS_6984.jpg&f=1&nofb=1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, quasi. Illo ratione error blanditiis hic rerum vitae tenetur architecto, ducimus aspernatur quam nostrum unde veniam at saepe aut iure sit, facilis, temporibus repudiandae velit. Cumque?',
        expertise: 'Body transformation, weight loss, proper nutrition',
        sessionTime: 45,
        sessionPrice: 250,
        monthPrice: 2500,
        emailAddress: 'testcoach@testcoach.com',
    },
    {
        id: '4',
        title: 'Lucy Cheng',
        certificate: 'AFAA Certified Personal Fitness Trainer',
        image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fqodebrisbane.com%2Fwp-content%2Fuploads%2F2019%2F07%2FThis-is-not-a-person-2-1.jpeg&f=1&nofb=1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod vel consectetur hic velit odio voluptatibus accusantium a rem? Unde officia exercitationem vel, laborum quisquam ex asperiores optio sequi adipisci hic fugiat sapiente delectus harum quia eius sed repudiandae maxime sunt!',
        expertise: 'Fitness, code moscles building, yoga',
        sessionTime: 45,
        sessionPrice: 175,
        monthPrice: 2000,
        emailAddress: 'testcoach@testcoach.com',
    },
    {
        id: '5',
        title: 'Paul Blank',
        certificate: 'ACSM and ACSM-CPT Certified Personal Trainer',
        image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.pixabay.com%2Fphoto%2F2014%2F07%2F09%2F10%2F04%2Fman-388104_640.jpg&f=1&nofb=1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa, dicta dignissimos! Ab illum, nihil praesentium culpa corrupti aliquid deleniti iure.',
        expertise: 'Power lifting, weight loss, endurance',
        sessionTime: 45,
        sessionPrice: 100,
        monthPrice: 1000,
        emailAddress: 'testcoach@testcoach.com',
    },
    {
        id: '6',
        title: 'Mark O\'Kelly',
        certificate: 'ACSM and ACSM-CPT Certified Personal Trainer',
        image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fjooinn.com%2Fimages%2Fman39s-face-11.jpg&f=1&nofb=1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa, dicta dignissimos! Ab illum, nihil praesentium culpa corrupti aliquid deleniti iure.',
        expertise: 'Power lifting, weight loss, endurance',
        sessionTime: 60,
        sessionPrice: 400,
        monthPrice: 5000,
        emailAddress: 'testcoach@testcoach.com',
    },
    {
        id: '7',
        title: 'Kelly Morgan',
        certificate: 'ACSM and ACSM-CPT Certified Personal Trainer',
        image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fqodebrisbane.com%2Fwp-content%2Fuploads%2F2019%2F07%2FThis-is-not-a-person-10-1.jpeg&f=1&nofb=1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa, dicta dignissimos! Ab illum, nihil praesentium culpa corrupti aliquid deleniti iure.',
        expertise: 'Power lifting, weight loss, endurance',
        sessionTime: 60,
        sessionPrice: 300,
        monthPrice: 4000,
        emailAddress: 'testcoach@testcoach.com',
    },
    {
        id: '8',
        title: 'Ben Clark',
        certificate: 'ACSM and ACSM-CPT Certified Personal Trainer',
        image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi2-prod.mirror.co.uk%2Fincoming%2Farticle5423743.ece%2FALTERNATES%2Fs615b%2FMOST-BEAUTIFUL-FACES.jpg&f=1&nofb=1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa, dicta dignissimos! Ab illum, nihil praesentium culpa corrupti aliquid deleniti iure.',
        expertise: 'Power lifting, weight loss, endurance',
        sessionTime: 45,
        sessionPrice: 200,
        monthPrice: 2000,
        emailAddress: 'testcoach@testcoach.com',
    },

]